#!/usr/bin/env python3
"""
run_scenario.py — end-to-end critical test of the orchestration loop and every handoff.

It drives the REAL deterministic scripts (validate_envelope, consolidate, verify, judge,
frontier) through the full loop — decompose stop-conditions -> fan-out (simulated) ->
validate -> consolidate -> adversarial verify -> judge -> frontier-expand -> loop/stop —
using scripted "agent" envelopes as stand-ins for live sub-agents. Agents are simulated
(not live LLMs) precisely so the test is deterministic and repeatable.

INDEPENDENT VALIDATION (validate the test without trusting the run):
  1. Structured oracle — fixtures/oracle.json states the expected final state, authored by
     hand from the fixtures (NOT generated by this pipeline). A reviewer can read the
     fixtures + oracle and confirm the oracle is correct without running anything.
  2. Property invariants — checks that must hold for ANY run regardless of the oracle values
     (citable provenance, no refuted key survives, no fabrication, conflicts preserved,
     determinism). These validate correctness independent of the specific expected answer.
  3. Pinned hash — oracle.json pins the sha256 of each scenario's final consolidated JSON.
     Reproduction must match the pin byte-for-byte.

Run:
  python3 run_scenario.py            # check both scenarios against the oracle; exit 0/1
  python3 run_scenario.py --emit     # print the actual final JSON + sha256 (to author/repin)
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPTS = HERE.parent / "scripts"
FIXTURES = HERE / "fixtures"
sys.path.insert(0, str(SCRIPTS))

from validate_envelope import validate_envelope          # noqa: E402
from consolidate import consolidate                      # noqa: E402
from verify import tally, apply_verdicts                 # noqa: E402
from judge import composite                              # noqa: E402
from frontier import expand_frontier                     # noqa: E402

HARD_CAPS = {"size_cap_reached", "depth_cap_reached"}


def _sig(s: str) -> str:
    return " ".join(str(s).lower().split())


def run(scenario: dict) -> dict:
    """Drive the full loop over a scenario; return {final, meta}. Deterministic."""
    run_id = scenario["run_id"]
    stop_defaults = scenario["stop_defaults"]
    agents = scenario["agents"]
    judge_scores = scenario.get("judge_scores", {})
    skeptic_votes = scenario.get("skeptic_votes", {})

    wave_approvals = scenario.get("wave_approvals", {})
    scopes = list(scenario["initial_scopes"])
    seen: list[str] = []
    accumulated: list[dict] = []
    rejected: list[dict] = []
    wave = 0
    dispatched = 0
    dry_streak = 0
    stop_reason = None
    unsatisfied = False
    proposed_scopes: list[str] = []

    while True:
        wave += 1
        # SPAWN GATE: agents never spawn agents. Wave 1 is the human-initiated task; every
        # recursive wave beyond it needs express human approval of the manager's proposal.
        # Without approval the loop halts and surfaces the recommendation — it never spawns.
        if wave > 1 and not bool(wave_approvals.get(str(wave), False)):
            stop_reason = "awaiting_human_approval"
            proposed_scopes = list(scopes)
            break
        dispatched += 1
        # 1. Fan-out (handoff DOWN): dispatch each scope to its simulated agent.
        envs = [agents[s] for s in scopes if s in agents]
        # 2. Validate (handoff UP through the anti-drift gate).
        valid = []
        for e in envs:
            v = validate_envelope(e)
            if v["valid"]:
                valid.append(e)
            else:
                rejected.append({"task_id": v.get("task_id"), "violations": v["violations"]})
        accumulated.extend(valid)
        seen.extend(scopes)

        # 3. Judge this wave's quality.
        jr = composite(judge_scores.get(str(wave), {"coverage": 0, "consistency": 0,
                                                     "provenance": 0, "saturation": 0}))
        # 4. Frontier-expand: dedup residual leads vs seen -> next wave or stop.
        exp = expand_frontier(valid, seen, wave, stop_defaults, len(accumulated), dry_streak)
        dry_streak = exp["dry_streak"]

        # 5. Stop logic: hard caps end it; else leads WIN (never cut short by the judge);
        #    a dry frontier always stops (the loop never invents leads) — the judge only
        #    labels the dry stop as satisfied ('saturated') or unsatisfied ('frontier_exhausted').
        if exp["stop_condition"] in HARD_CAPS:
            stop_reason = exp["stop_condition"]
            break
        if exp["next_scopes"]:
            scopes = [s["scope"] for s in exp["next_scopes"]]
            continue
        stop_reason = "saturated" if jr["recommendation"] == "stop" else "frontier_exhausted"
        unsatisfied = jr["recommendation"] != "stop"
        break

    # 6. Consolidate the full accumulated set (residual reconciled against covered scopes).
    pre = consolidate(run_id, accumulated, stop_reason, covered_scopes=seen)
    pre_conflict_keys = sorted(f["key"] for f in pre["findings"] if f["status"] == "conflict")

    # 7. Adversarial verify every pending_verification key, then fold verdicts back.
    verdicts = {k: tally(**skeptic_votes[k]) for k in pre["pending_verification"] if k in skeptic_votes}
    final = apply_verdicts(pre, verdicts)

    # 8. Record an unmet-quality note when the run stopped dry but the judge wanted more.
    if unsatisfied:
        mr = final.get("minority_report") or {"decision_log": {}, "conflicts": [],
                                              "failed_to_merge": [], "residual_uncertainty": []}
        mr["residual_uncertainty"] = mr.get("residual_uncertainty", []) + [{
            "statement": "frontier exhausted but wave-judge was not satisfied",
            "what_would_resolve_it": "re-scope the task or unblock the blocked source",
            "impact_if_wrong": "coverage may be insufficient",
        }]
        final["minority_report"] = mr

    # 8b. Spawn gate reached: surface the manager's recommendation; nothing was spawned.
    recommendation = None
    if stop_reason == "awaiting_human_approval":
        recommendation = {
            "recommend": "spawn the next wave over the proposed scopes",
            "proposed_scopes": proposed_scopes,
            "why": "residual leads remain; agents cannot self-spawn — human approval required",
        }
        mr = final.get("minority_report") or {"decision_log": {}, "conflicts": [],
                                              "failed_to_merge": [], "residual_uncertainty": []}
        mr["residual_uncertainty"] = mr.get("residual_uncertainty", []) + [{
            "statement": "awaiting human approval to spawn next wave over: " + ", ".join(proposed_scopes),
            "what_would_resolve_it": "human approves the manager's recommendation",
            "impact_if_wrong": "proposed scopes remain uncovered",
        }]
        final["minority_report"] = mr

    valid_keys = sorted({f["key"] for e in accumulated for f in e.get("findings", [])})
    meta = {
        "waves": dispatched,
        "stop_reason": stop_reason,
        "rejected": rejected,
        "recommendation": recommendation,
        "pre_verify_pending": pre["pending_verification"],
        "pre_verify_conflict_keys": pre_conflict_keys,
        "valid_finding_keys": valid_keys,
    }
    return {"final": final, "meta": meta}


def _hash(obj) -> str:
    return hashlib.sha256(json.dumps(obj, sort_keys=True, ensure_ascii=False).encode()).hexdigest()


def _check_properties(name: str, final: dict, meta: dict, scenario: dict) -> list[str]:
    """Fixture-independent invariants — true for ANY correct run."""
    fails = []
    vague = {"", "internal", "various", "unknown", "n/a", "na", "none", "-", "tbd", "misc", "general"}

    # P1: every final finding has a specific citable provenance
    for f in final["findings"]:
        for p in f.get("provenance", []):
            if str(p).strip().lower() in vague:
                fails.append(f"[{name}] P1 uncitable provenance survived: {f['key']} -> {p}")

    # P2: no refuted key survives in findings
    refuted = {n["affected_keys"][0] for n in (final.get("minority_report") or {}).get("failed_to_merge", [])
               if n.get("affected_keys")}
    for f in final["findings"]:
        if f["key"] in refuted:
            fails.append(f"[{name}] P2 refuted key still in findings: {f['key']}")

    # P3: complete => no blocks and no residual
    cov = final["coverage"]
    if cov["state"] == "complete" and (cov["agents_blocked"] > 0 or final["residual_frontier"]):
        fails.append(f"[{name}] P3 'complete' with blocks/residual")

    # P4: every pre-verify conflict was preserved with >=2 variants (never averaged)
    for f in consolidate(scenario["run_id"],
                         [e for e in _accumulated_for(scenario)], None,
                         covered_scopes=None)["findings"]:
        if f["status"] == "conflict" and not (isinstance(f["value"], list) and len(f["value"]) >= 2):
            fails.append(f"[{name}] P4 conflict not preserved as >=2 variants: {f['key']}")

    # P5: human_review_required true on the final object
    if final.get("human_review_required") is not True:
        fails.append(f"[{name}] P5 final missing human_review_required:true")

    # P7: no fabrication — every final key came from some validated agent finding
    for f in final["findings"]:
        if f["key"] not in meta["valid_finding_keys"]:
            fails.append(f"[{name}] P7 fabricated key not from any agent: {f['key']}")

    # P8: the malformed/uncitable envelope's key never appears
    for f in final["findings"]:
        if f["key"] == "FAKE":
            fails.append(f"[{name}] P8 rejected envelope's finding survived: FAKE")

    # P9: no agent self-spawned — when the run halts awaiting approval, the proposed scopes
    # were NOT dispatched, so no finding originates from them (P7 already ties every finding
    # to a dispatched agent; here we assert the halt truly withheld the spawn).
    if meta["stop_reason"] == "awaiting_human_approval":
        if not final["residual_frontier"]:
            fails.append(f"[{name}] P9 awaiting approval but no residual leads surfaced")
        if not (meta.get("recommendation") or {}).get("proposed_scopes"):
            fails.append(f"[{name}] P9 awaiting approval but no recommendation surfaced")
    return fails


def _accumulated_for(scenario: dict) -> list[dict]:
    """Validated envelopes across the whole run (for the P4 conflict re-check)."""
    out = []
    for e in scenario["agents"].values():
        if validate_envelope(e)["valid"]:
            out.append(e)
    return out


def _check_oracle(name: str, final: dict, meta: dict, oc: dict) -> list[str]:
    """Exact-match against the hand-authored oracle."""
    fails = []
    cov = final["coverage"]
    exp = oc["coverage"]
    for k in ("state", "agents_total", "agents_blocked"):
        if cov[k] != exp[k]:
            fails.append(f"[{name}] oracle.coverage.{k}: got {cov[k]} want {exp[k]}")
    got_keys = sorted(f["key"] for f in final["findings"])
    if got_keys != oc["finding_keys"]:
        fails.append(f"[{name}] oracle.finding_keys: got {got_keys} want {oc['finding_keys']}")
    if meta["stop_reason"] != oc["stop_reason"]:
        fails.append(f"[{name}] oracle.stop_reason: got {meta['stop_reason']} want {oc['stop_reason']}")
    if meta["waves"] != oc["waves"]:
        fails.append(f"[{name}] oracle.waves: got {meta['waves']} want {oc['waves']}")
    if final["pending_verification"] != oc["pending_after_verify"]:
        fails.append(f"[{name}] oracle.pending_after_verify: got {final['pending_verification']} "
                     f"want {oc['pending_after_verify']}")
    if len(meta["rejected"]) != oc["rejected_count"]:
        fails.append(f"[{name}] oracle.rejected_count: got {len(meta['rejected'])} want {oc['rejected_count']}")
    for rk in oc.get("refuted_keys", []):
        refuted = {n["affected_keys"][0] for n in (final.get("minority_report") or {}).get("failed_to_merge", [])
                   if n.get("affected_keys")}
        if rk not in refuted:
            fails.append(f"[{name}] oracle.refuted_keys: {rk} not recorded as refuted")
    if "ao_confidence" in oc:
        ao = next((f for f in final["findings"] if f["key"] == "AO"), None)
        if not ao or ao["confidence"] != oc["ao_confidence"]:
            fails.append(f"[{name}] oracle.ao_confidence: got {ao and ao['confidence']} want {oc['ao_confidence']}")
    if "proposed_scopes" in oc:
        got = sorted((meta.get("recommendation") or {}).get("proposed_scopes", []))
        if got != sorted(oc["proposed_scopes"]):
            fails.append(f"[{name}] oracle.proposed_scopes: got {got} want {sorted(oc['proposed_scopes'])}")
    return fails


def main(argv=None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    scenarios = {"A": "scenario_a.json", "B": "scenario_b.json", "C": "scenario_c.json"}
    emit = "--emit" in argv

    if emit:
        for name, fn in scenarios.items():
            sc = json.loads((FIXTURES / fn).read_text())
            r = run(sc)
            print(f"\n===== {name} final =====")
            print(json.dumps(r["final"], indent=2, sort_keys=True, ensure_ascii=False))
            print(f"sha256({name}) = {_hash(r['final'])}")
            print(f"meta({name}) = {json.dumps(r['meta'], sort_keys=True)}")
        return 0

    oracle = json.loads((FIXTURES / "oracle.json").read_text())
    all_fails: list[str] = []
    for name, fn in scenarios.items():
        sc = json.loads((FIXTURES / fn).read_text())
        r1 = run(sc)
        r2 = run(sc)  # P6: determinism
        if _hash(r1["final"]) != _hash(r2["final"]):
            all_fails.append(f"[{name}] P6 non-deterministic: two runs differ")
        final, meta = r1["final"], r1["meta"]

        f_props = _check_properties(name, final, meta, sc)
        f_oracle = _check_oracle(name, final, meta, oracle[name])
        pin = oracle[name].get("final_sha256")
        f_hash = []
        if pin and pin != "PIN" and _hash(final) != pin:
            f_hash = [f"[{name}] pinned sha256 mismatch: got {_hash(final)} want {pin}"]

        scen_fails = f_props + f_oracle + f_hash
        all_fails += scen_fails
        status = "PASS" if not scen_fails else "FAIL"
        print(f"[{status}] scenario {name}: {meta['waves']} wave(s), stop={meta['stop_reason']}, "
              f"coverage={final['coverage']['state']}, findings={sorted(f['key'] for f in final['findings'])}, "
              f"rejected={len(meta['rejected'])}, sha256={_hash(final)[:12]}")
        for f in scen_fails:
            print(f"    ✗ {f}")

    print()
    if all_fails:
        print(f"RESULT: FAIL — {len(all_fails)} assertion(s) failed.")
        return 1
    print("RESULT: PASS — all scenarios match the oracle and every property invariant holds.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
