#!/usr/bin/env python3
"""
metrics.py — regenerable scoreboard: one screen that says what dbz contains,
how strongly its evidence is corroborated, and how fresh its sources are.

Reads only committed registries + build artifacts (grc_manifest.json / grc.db
when present) and the benchmark script's measured table; writes docs/METRICS.md
with a generated-file banner. Numbers here are DERIVED, so the file is not
registered in doc_claims (count_truth checks asserted numbers; this file is
regenerated, and sync_check invariant 13 fails when regeneration would differ).

Usage:
  python3 tools/metrics.py            # rewrite docs/METRICS.md
  python3 tools/metrics.py --check    # exit 1 if the committed doc is stale
"""

import argparse
import json
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "METRICS.md"
MANIFEST = ROOT / "cross-mapping" / "output" / "grc_manifest.json"
DB = ROOT / "cross-mapping" / "output" / "grc.db"

BANNER = ("<!-- GENERATED by tools/metrics.py — do not edit by hand; regenerate after any "
          "build or registry change. Guarded by sync_check invariant 13. -->")


def _load(p):
    return json.loads((ROOT / p).read_text(encoding="utf-8"))


def gather():
    m = {}
    feeds = _load("canonical-sources/feed_registry.json")["feeds"]
    m["feeds"] = len(feeds)
    m["feeds_auto_fetch"] = sum(1 for e in feeds.values()
                                if isinstance(e, dict) and e.get("auto_fetch"))
    status = {}
    for e in feeds.values():
        if isinstance(e, dict):
            s = e.get("artifact_status", "metadata_only")
            status[s] = status.get(s, 0) + 1
    m["feed_status"] = dict(sorted(status.items()))
    m["horizon"] = len(_load("canonical-sources/anticipated_updates.json")["records"])
    m["atoms"] = len(_load("skills/atoms/atoms.json")["atoms"])
    m["overlays"] = len([p for p in (ROOT / "canonical-sources" / "overlays").rglob("*.json")
                         if p.name != "overlay.schema.json"])
    m["doc_claims"] = len(_load("canonical-sources/doc_claims.json")["claims"])

    # uncertainty honesty ratio
    ledger = (ROOT / "canonical-sources" / "uncertainty_ledger.jsonl").read_text(
        encoding="utf-8").strip().splitlines()
    uncertainties = [json.loads(l) for l in ledger if l.strip()]
    conf_lines = (ROOT / "canonical-sources" / "confirmations.jsonl").read_text(
        encoding="utf-8").strip().splitlines()
    confirmations = [json.loads(l) for l in conf_lines
                     if l.strip() and '"_schema"' not in l.split(":", 1)[0]]
    decided = {c.get("uncertainty_id") for c in confirmations if c.get("uncertainty_id")}
    m["uncertainties"] = len(uncertainties)
    m["uncertainties_decided"] = len(decided)

    if MANIFEST.exists():
        man = json.loads(MANIFEST.read_text(encoding="utf-8"))
        rc = man.get("row_counts", {})
        import re as _re
        _src = (ROOT / "cross-mapping" / "engine" / "build_db.py").read_text(encoding="utf-8")
        _mv = _re.search(r'SCHEMA_VERSION\s*=\s*"([^"]+)"', _src)
        m["schema_version"] = _mv.group(1) if _mv else man.get("schema_version")
        m["db_tables"] = len(rc)
        for k in ("controls", "enhancements", "disa_ccis", "master_mappings",
                  "overlap_matrix", "stig_catalog", "stig_rules",
                  "fedramp_ksi", "fedramp_ksi_controls", "olir_hub_edges"):
            m[k] = rc.get(k)
    if DB.exists():
        c = sqlite3.connect(DB)
        m["master_frameworks"] = c.execute(
            "SELECT COUNT(DISTINCT fw) FROM (SELECT fw_a fw FROM master_mappings "
            "UNION SELECT fw_b FROM master_mappings)").fetchone()[0]
        m["by_tier"] = dict(c.execute(
            "SELECT tier, COUNT(*) FROM master_mappings GROUP BY 1 ORDER BY 2 DESC"))
        m["by_state"] = dict(c.execute(
            "SELECT evidence_state, COUNT(*) FROM master_mappings GROUP BY 1 ORDER BY 2 DESC"))
        c.close()

    # benchmark headline from the generated table in docs/BENCHMARK.md
    bench = (ROOT / "docs" / "BENCHMARK.md").read_text(encoding="utf-8")
    m["benchmark_lines"] = [l for l in bench.splitlines()
                            if l.startswith("| SOC 2 ×")]
    return m


def render(m):
    L = [BANNER, "", "# METRICS — the scoreboard", ""]
    L.append("A regenerable one-screen summary of what dbz contains and how honest its evidence "
             "is. Asserted numbers elsewhere are guarded by `tools/count_truth.py`; everything "
             "here is derived by `tools/metrics.py`.")
    L += ["", "## Contents", ""]
    if m.get("schema_version"):
        L.append(f"- **grc.db** schema {m['schema_version']}, {m['db_tables']} tables")
        L.append(f"- **Spine:** {m.get('controls')} controls + {m.get('enhancements')} "
                 "enhancements (800-53 r5)")
        L.append(f"- **Master surface:** {m.get('master_mappings')} edges across "
                 f"{m.get('master_frameworks')} frameworks; matrix {m.get('overlap_matrix')} pairs")
        L.append(f"- **Depth:** {m.get('disa_ccis')} CCIs · {m.get('stig_catalog')} STIG "
                 f"benchmarks / {m.get('stig_rules')} rules · {m.get('fedramp_ksi')} FedRAMP KSIs "
                 f"({m.get('fedramp_ksi_controls')} stated edges) · "
                 f"{m.get('olir_hub_edges')} OLIR-hub composed edges")
    L.append(f"- **Keep-current:** {m['feeds']} feeds ({m['feeds_auto_fetch']} auto-fetch) · "
             f"{m['horizon']} horizon records")
    L.append(f"- **Tooling:** {m['atoms']} atoms · {m['overlays']} overlays · "
             f"{m['doc_claims']} machine-checked doc claims")
    if m.get("by_tier"):
        L += ["", "## Master edges by provenance tier", ""]
        L += [f"- `{t}`: {n}" for t, n in m["by_tier"].items()]
    if m.get("by_state"):
        L += ["", "## Master edges by evidence state (corroboration ladder)", ""]
        L += [f"- `{s}`: {n}" for s, n in m["by_state"].items()]
    L += ["", "## Honesty ledger", "",
          f"- Open uncertainties recorded: **{m['uncertainties']}**; decided via the "
          f"confirmation ledger: **{m['uncertainties_decided']}**. Uncertain fields stay "
          "blank/flagged — never guessed (see `protocol-layer/evidence-standards.md`)."]
    L += ["", "## Accuracy headline (measured — full table in docs/BENCHMARK.md)", ""]
    L += ["| Pair | … | metrics |", "|---|---|---|"] and []
    if m["benchmark_lines"]:
        L.append("```")
        L += m["benchmark_lines"]
        L.append("```")
    L += ["", "## Feed status breakdown", ""]
    L += [f"- `{s}`: {n}" for s, n in m["feed_status"].items()]
    L.append("")
    return "\n".join(L)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    if a.check and not (MANIFEST.exists() and DB.exists()):
        # Fresh checkout (CI has no build artifacts): regeneration would legitimately
        # differ, so the check degrades honestly — same pattern as count_truth's
        # DB-dependent claims. The full check runs wherever a build exists.
        print("[metrics check skipped] grc.db/grc_manifest.json not built (fresh checkout)")
        return 0
    text = render(gather())
    if a.check:
        if not DOC.exists() or DOC.read_text(encoding="utf-8") != text:
            print("[metrics drift] docs/METRICS.md is stale — regenerate with tools/metrics.py")
            return 1
        print("[metrics OK] docs/METRICS.md matches the data")
        return 0
    DOC.write_text(text, encoding="utf-8")
    print(f"wrote {DOC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
